### ISSUE TITLE
Ordering of keys in structure JSON file

### ISSUE THREAD

**Issue by no-more-secrets** [pavelbel/smcol_saves_utility#4]
The file smcol_sav_struct.json appears to rely on the ordering of keys in objects, but from what I understand JSON object keys are not ordered.  How does your python script work when it parses the JSON?  Does it just get lucky and the keys are in the right order?  E.g. see here: https://stackoverflow.com/questions/10844064/items-in-json-object-are-out-of-order-using-json-dumps

**Comment by no-more-secrets** [comment]
I'm not a python expert, but it appears that using python 3.8+ (?) might automatically preserve the ordering of keys in tables, since the python dictionary does the same.  If that is the case, namely that you are relying on that, then you might want to give a disclaimer somewhere since not all JSON parsers preserve key ordering, since the JSON spec does not require it.  Or maybe you might consider prefixing all keys with a fixed-width number in order to allow people or recover the correct ordering after using a JSON parser that does not preserve ordering.

**Comment by pavelbel** [comment]
Thanks for code review) Yes I rely on python 3.7+ preserving dict's keys order and its json module that does the same for JSON objects: why not use it if it exists? I'm not making a universal lib required to strictly follow the standards. It's just a tool for an old game... Anyway I'll add a corresponding note to readme

**Comment by no-more-secrets** [comment]
@pavelbel Thanks!
