### ISSUE TITLE
`terrain_5bit_type` might need more values.

### ISSUE THREAD

**Issue by no-more-secrets** [pavelbel/smcol_saves_utility#7]
@pavelbel I've attached the file AMER2.MP which is the map of "America" that ships with the original game.  The first section of it contains the `TILE` array which is equivalent to the `TILE` section of the saved game.  However, the bytes in that section seem to use either the 4th bit or the 5th bit to indicate a forested tile.  For example, a scrub forest (desert with forest) can be represented either as `0b01001` or as `0b10001`, and both appear in the map data.  Here is what I needed to do in order to get those map files to parse correctly with my own tool that uses your schema:
```json
"terrain_5bit_type":
{
    "tu ":  "00000",
    "de ":  "00001",
    "pl ":  "00010",
    "pr ":  "00011",
    "gr ":  "00100",
    "sa ":  "00101",
    "sw ":  "00110",
    "mr ":  "00111",
    "tuF":  "01000",
    "deF":  "01001",
    "plF":  "01010",
    "prF":  "01011",
    "grF":  "01100",
    "saF":  "01101",
    "swF":  "01110",
    "mrF":  "01111",
    "tuF2": "10000",
    "deF2": "10001",
    "plF2": "10010",
    "prF2": "10011",
    "grF2": "10100",
    "saF2": "10101",
    "swF2": "10110",
    "mrF2": "10111",
    "arc":  "11000",
    "~~~":  "11001",
    "~:~":  "11010"
},
```
You can see that for each of the forested ones I have added a second equivalent one ending in 2.  The game's map editor seems to know how to parse these, since I can load this file into the map editor and use it in the game.

Have you seen these variations before?  I wonder if we need to reinterpret the bits in `terrain_5bit_type` somehow.
[AMER2.zip](https://github.com/pavelbel/smcol_saves_utility/files/13330753/AMER2.zip)

**Comment by no-more-secrets** [comment]
It turns out that if you load that file into the map editor and then just save it again as a new file, the new file will have the "standard" convention for the forested tiles (i.e., `tuF` instead of `tuF2`).  So that is a workaround.  But I'm curious to know why there were two formats.

**Comment by pavelbel** [comment]
Oh, nice. I didn't know. Yes, these are valid tile values, supported by game. I've added them to `terrain_5bit_type` values as `..W` (= woods), not `..F2` - to preserve 3 chars name length.

Also fixed marsh <-> swamp swap.

**Comment by no-more-secrets** [comment]
Thanks, looks good -- except I think we also need to swap the order of the non-forested marsh<->swamp, i.e. currently we have:
```json
   "sw ": "00110",
   "mr ": "00111",
```
but those need to be swapped as well, confirmed by experimenting with the map editor.

**Comment by pavelbel** [comment]
Ah, yeah, missed this one. Thanks. Fixed.
